package khvatid.wallpaper.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF7E5700)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDEAB)
val md_theme_light_onPrimaryContainer = Color(0xFF271900)
val md_theme_light_secondary = Color(0xFF006491)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFC9E6FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001E2F)
val md_theme_light_tertiary = Color(0xFF7D5700)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDEAB)
val md_theme_light_onTertiaryContainer = Color(0xFF271900)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFCFE)
val md_theme_light_onBackground = Color(0xFF191C1E)
val md_theme_light_outline = Color(0xFF72777F)
val md_theme_light_inverseOnSurface = Color(0xFFF0F1F3)
val md_theme_light_inverseSurface = Color(0xFF2E3133)
val md_theme_light_inversePrimary = Color(0xFFFFBA32)
//val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF7E5700)
val md_theme_light_outlineVariant = Color(0xFFC2C7CF)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_surface = Color(0xFFF8F9FC)
val md_theme_light_onSurface = Color(0xFF191C1E)
val md_theme_light_surfaceVariant = Color(0xFFDEE3EB)
val md_theme_light_onSurfaceVariant = Color(0xFF42474E)

val md_theme_dark_primary = Color(0xFFFFBA32)
val md_theme_dark_onPrimary = Color(0xFF422C00)
val md_theme_dark_primaryContainer = Color(0xFF5F4100)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDEAB)
val md_theme_dark_secondary = Color(0xFF89CEFF)
val md_theme_dark_onSecondary = Color(0xFF00344D)
val md_theme_dark_secondaryContainer = Color(0xFF004C6E)
val md_theme_dark_onSecondaryContainer = Color(0xFFC9E6FF)
val md_theme_dark_tertiary = Color(0xFFFBBB42)
val md_theme_dark_onTertiary = Color(0xFF422C00)
val md_theme_dark_tertiaryContainer = Color(0xFF5F4100)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDEAB)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1E)
val md_theme_dark_onBackground = Color(0xFFE1E2E5)
val md_theme_dark_outline = Color(0xFF8C9199)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1E)
val md_theme_dark_inverseSurface = Color(0xFFE1E2E5)
val md_theme_dark_inversePrimary = Color(0xFF7E5700)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFBA32)
val md_theme_dark_outlineVariant = Color(0xFF42474E)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_surface = Color(0xFF111416)
val md_theme_dark_onSurface = Color(0xFFC5C6C9)
val md_theme_dark_surfaceVariant = Color(0xFF42474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C7CF)


//val seed = Color(0xFFE19F00)